name: sccml
channels:
  - conda-forge

dependencies:
  - pandas
  - python
  - yaml
  - matplotlib
  - seaborn
  - numpy
  - pip
  - scipy
  - scikit-learn
  - scikit-image
  - opencv
  - scanpy
  - pip:
    - louvin
    - spyteomics
    - xgboost
    - shap
